#!/usr/bin/env bash
set -e

echo "$1" >>/fluentd/invokes

while read -r line; do
  if [ "$line" = "" ]; then
    continue
  else
    namespace=$(echo "$line" | cut -d$'\t' -f1)
    log=$(echo "$line" | cut -d$'\t' -f2-)

    echo "$log" >> "/fluentd/$namespace.log"
    tail -n 3 "/fluentd/$namespace.log" > "/fluentd/$namespace.log.trimmed"
    mv "/fluentd/$namespace.log.trimmed" "/fluentd/$namespace.log"
  fi
done <"$1"
