---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer
  namespace: logstream
spec:
  selector:
    matchLabels:
      app: writer
  template:
    metadata:
      labels:
        app: writer
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: fluentd
          image: mattipaksula/logstream-writer
---
apiVersion: v1
kind: Service
metadata:
  name: writer
  namespace: logstream
spec:
  selector:
    app: writer
  ports:
    - port: 24224
      targetPort: 24224
