---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: router
  namespace: logstream
spec:
  replicas: 2
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: fluentd
          image: mattipaksula/logstream-router
---
apiVersion: v1
kind: Service
metadata:
  name: router
  namespace: logstream
spec:
  selector:
    app: router
  ports:
    - port: 24224
      targetPort: 24224
